site_url: "https://justin.albrethseng.com/"
site_name: Justin Albrethsen's site
nav:
 - Home: index.md
 - Publications: publications.md
 - Projects:
   - Tiny Linux: 'Minimal Linux.md' 
   - Ubuntu Thin Client: 'Ubuntu thin client.md'
   - Wyoming on Echo Dot: 'EchoWyoming.md'
 - Reference Materials:
    - Linux Commands: 'Linux commands.md'
    - Linux Tunnels: 'Linux tunnels.md'
    - Proxmox Resize Disk: 'Proxmox Resize Disk.md'
    - Proxmox Import ova: 'Proxmox import parrot .ova.md'
    - SSH Commands: SSH.md
    - FPGA: 'FPGA Tang Nano 9K.md'
